version: '2'

volumes:
  caddy: {}

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    env_file: .env
    volumes:
      - ./db:/app/db
      - /etc/localtime:/etc/localtime:ro

  caddy:
    build: ./compose/caddy
    depends_on:
      - flask
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - caddy:/root/.caddy
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

  routine:
    build:
      context: .
      dockerfile: ./compose/routine/Dockerfile
    env_file: .env
    volumes:
      - ./db:/app/db
      - /etc/localtime:/etc/localtime:ro

