version: '3'

volumes:
  caddy: {}
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_backup:/backups
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro

  caddy:
    build: ./compose/caddy
    depends_on:
      - flask
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - caddy:/root/.caddy
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

  routine:
    build:
      context: .
      dockerfile: ./compose/routine/Dockerfile
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro

